export enum EducationLevel {
    HIGH_SCHOOL = 'HIGH_SCHOOL',
    ASSOCIATE = 'ASSOCIATE',
    BACHELOR = 'BACHELOR',
    MASTER = 'MASTER',
    PHD = 'PHD',
    CERTIFICATE = 'CERTIFICATE',
    BOOTCAMP = 'BOOTCAMP'
}