export enum InterestCategory {
    LEARNING = 'LEARNING',
    TECHNOLOGY = 'TECHNOLOGY',
    CULTURE = 'CULTURE',
    ENTERTAINMENT = 'ENTERTAINMENT',
    SCIENCE = 'SCIENCE',
    BUSINESS = 'BUSINESS',
    ARTS = 'ARTS',
    HEALTH = 'HEALTH',
    SPORTS = 'SPORTS',
    EDUCATION = 'EDUCATION',
    ENVIRONMENT = 'ENVIRONMENT',
    POLITICS = 'POLITICS',
    TRAVEL = 'TRAVEL',
    FOOD = 'FOOD'
}