export enum ProjectStatus {
    PLANNING = 'PLANNING',
    DEVELOPMENT = 'DEVELOPMENT',
    TESTING = 'TESTING',
    PRODUCTION = 'PRODUCTION',
    MAINTENANCE = 'MAINTENANCE',
    ARCHIVED = 'ARCHIVED'
}