package com.example.portofolio.entity.enums;

public enum AchievementType {
    PROJECT, HOBBY, VOLUNTEER, COMPETITION, RECOGNITION,ACADEMIC,PROFESSIONAL,TECHNICAL
    ,RESEARCH,LEADERSHIP,CERTIFICATION,PUBLICATION,PATENT,AWARD
}
