package com.example.portofolio.entity.enums;

public enum EntityType {
    SKILL, PROJECT, HIGHLIGHT,CERTIFICATE, EDUCATION,LEARNING_PROGRESS, HOBBY, PERSONAL,VOLUNTEER, INTEREST, ACHIEVEMENT, TECHNOLOGY, CONTACT_INFO
}
